from typing import Dict, List
import torch
import torch.optim as optim 
from torch.utils.data import DataLoader
from models.FieldEmbedding import FieldEmbedding
import pandas as pd 
import os
# from utils.data_loader_gnn import GNNTrafficDataset, gnn_collate_fn
# from utils.data_loader_ptga import GNNTrafficDataset
from utils.data_loader_ptga_le import GNNTrafficDataset
from models.ProtocolTreeGAttention_le import HierarchicalMoE
# from transformers import get_linear_schedule_with_warmup
from utils.loss_functions import FocalLoss
import numpy as np
import random 
import copy
import gc
from utils.dataframe_tools import stratified_hybrid_sample_from_csv_stream
from utils.dataframe_tools import stratified_flow_sample_from_csv_stream
from utils.flow_batch_components import (
    FlowCentricBatchSampler,
    FlowLogitAttentionPool,
    FlowReprLogitAggregator,
)
from utils.train_eval_flow import (
    set_module_requires_grad,
    train_one_epoch,
    evaluate,
    collect_packet_logits_labels,
    evaluate_flow_aggregation_from_packet_logits,
    compute_dataset_expert_importance,
)

# os.environ['CUDA_LAUNCH_BLOCKING'] = "1" 
# os.environ['TORCH_USE_CUDA_DSA'] = "1"

TORCH_LONG_MAX = torch.iinfo(torch.long).max
def robust_hex_to_int(x):
    """Safely convert a hex-like value to int; return 0 on invalid input."""
    if not pd.notna(x): return 0
    try:
         
        val_str = str(x).split('.')[0]
         
        val_str = val_str.lower().replace('0x','')
        if not val_str: return 0   
        return min(int(val_str, 16), TORCH_LONG_MAX)
    except ValueError:
        return 0   
    
def robust_timestamp_to_tsval(x):
    """
    Extract TSval from tcp.options.timestamp (format: 080a + TSval + TSecr).
    Return 0 when format is invalid.
    """
    if not pd.notna(x): return 0
    try:
         
        s = str(x).lower().replace('0x', '')
        
         
         
        if len(s) != 20 or not s.startswith('080a'):
            return 0   
            
         
        tsval_hex = s[4:12]
        
         
        return int(tsval_hex, 16)
    except (ValueError, TypeError):
        return 0   

def set_seed(seed_value: int, deterministic: bool = True):
    """
    Set all relevant random seeds for reproducibility.
    """
    print(f"Setting global seed to {seed_value}")
    random.seed(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed_value)
        torch.cuda.manual_seed_all(seed_value)   
        
        # Deterministic mode is reproducible but often slower.
        if deterministic:
            torch.backends.cudnn.benchmark = False
            torch.backends.cudnn.deterministic = True
        else:
            torch.backends.cudnn.benchmark = True
            torch.backends.cudnn.deterministic = False

def seed_worker(worker_id):
    """
    Initialize worker-level RNG state for DataLoader workers.
    """
     
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)




if __name__ == '__main__':
    SEED = 42
    DETERMINISTIC_TRAINING = False
    set_seed(SEED, deterministic=DETERMINISTIC_TRAINING)

     
    NUM_EPOCHS = 100
    SCALE_FACTOR = 1
    BATCH_SIZE = 1024 // SCALE_FACTOR
    # BATCH_SIZE = 512
    LEARNING_RATE = 1e-3
    WEIGHT_DECAY = 1e-4
    MAX_LEARNING_RATE = 1e-3
    DROPOUT_RATE = 0.1
    NUM_WORKERS = 4
    USE_AMP = True
    AMP_DTYPE_STR = 'fp16'  # 'fp16' or 'bf16'
    THROUGHPUT_PROFILE = 'cuda_low_ram'  # 'base' | 'high' | 'cuda_low_ram'
    DATALOADER_PREFETCH = 2
    PERSISTENT_WORKERS = True
    GNN_INPUT_DIM = 32 
    GNN_HIDDEN_DIM = 128
    PATIENCE = 5
    DIAGNOSE = False
    # DIAGNOSE = True
    stop_training = False

    USE_FLOW_FEATURES_THIS_RUN = True
    # USE_FLOW_FEATURES_THIS_RUN = False
    # USE_MAC_ADDRESS_THIS_RUN = True
    USE_MAC_ADDRESS_THIS_RUN = False
    # USE_IP_ADDRESS_THIS_RUN = True
    USE_IP_ADDRESS_THIS_RUN = False
    # USE_PORT_THIS_RUN = True
    USE_PORT_THIS_RUN = False
    # Optional distilled PTG spec generated by build_distilled_ptg.py.
    # Set to None to use original full PTG construction.
    DISTILLED_GRAPH_SPEC_PATH = None
    # Example:
    # DISTILLED_GRAPH_SPEC_PATH = os.path.join(
    #     "..", "Res", "distilled_ptg", "cstnet_tls_1.3",
    #     "cstnet_tls_1.3_ptgd_topk5_plusk_noroot_sink.json"
    # )
    ENABLE_FLOW_AGG_EVAL = True
    FLOW_AGG_USE_PROB_MEAN = True
    ENABLE_DIRECTIONAL_FLOW_CONTEXT = True
    # Lightweight mode: disable dual packet/flow metrics during epoch to reduce overhead.
    ENABLE_DUAL_LEVEL_METRICS = False
    TRAIN_TARGET = 'flow'  # 'packet' or 'flow' 
    FLOW_AGG_METHOD = 'repr_logits_attn'  # 'mean_logits' | 'learned_attn_logits' | 'repr_logits_attn' | 'soft_weighted_logits' | 'topk_mean_logits' | 'mean_probs' | 'logsumexp'
    FLOW_TOPK = 8
    FLOW_SOFT_TEMP = 1.2
    FLOW_ATTN_HIDDEN_DIM = 64
    FLOW_ATTN_DROPOUT = 0.1
    FLOW_REPR_LOGIT_USE_PROBS = True
    FLOW_REPR_USE_LOGIT_BRANCH = False
    FLOW_REPR_ATTN_TAU = 1.5
    FLOW_REPR_USE_RESIDUAL_MEAN = False
    FLOW_REPR_USE_LOGIT_RESIDUAL_BASELINE = False
    FLOW_REPR_LOGIT_RESIDUAL_INIT = 0.0
    FLOW_REPR_FIRST_N_PACKETS = 64
    FLOW_REPR_POOL_MODE = 'max'  # 'attn' | 'max' | 'mean'
    FLOW_REPR_DETACH_WARMUP_EPOCHS = 0
    FLOW_REPR_PERMANENT_DETACH = False
    FLOW_REPR_TRAIN_AGG_ONLY_EPOCHS = 0
    FLOW_REPR_GAMMA_CLAMP_MAX = 0.2
    ENABLE_VIRTUAL_SINK = True
    VIRTUAL_SINK_NAME = "__VIRTUAL_SINK__"
    FLOW_LOSS_USE_PACKET_AUX = True
    FLOW_PACKET_AUX_WEIGHT = 0.5
    ENABLE_FLOW_CENTRIC_BATCHING = True
    FLOW_CENTRIC_BATCH_FLOWS = 64
    FLOW_CENTRIC_PACKETS_PER_FLOW = FLOW_REPR_FIRST_N_PACKETS
    FLOW_CENTRIC_DROP_LAST = False
    FLOW_CENTRIC_LOW_RAM_SAFE_MODE = True
    STRATIFIED_TRAIN_SET = False
    STRATIFIED_VAL_TEST_SET = False
    # STRATIFIED_TRAIN_SET = True
    # STRATIFIED_VAL_TEST_SET = True
    SAMPLING_PROPORTION = 0.6
    SAMPLING_GRANULARITY = 'flow'  # 'flow' or 'packet'
    MIN_FLOWS_PER_CLASS = 5
    MAX_PACKETS_PER_FLOW_TRAIN = 256
    # MAX_PACKETS_PER_FLOW_EVAL = 256
    MAX_PACKETS_PER_FLOW_EVAL = MAX_PACKETS_PER_FLOW_TRAIN
    PREFER_LONG_FLOWS = True
    LONG_FLOW_PRIORITY_RATIO = 0.5
    # ABLATION_LAYERS = ['eth', 'ip', 'tcp', 'tls']
    ABLATION_LAYERS = ['ip', 'tcp', 'tls']
    BACKBONE_MODE = 'expert_local'  # 'expert_local' | 'global'

    FILTER_SHORT_ENTRIES = False

    if THROUGHPUT_PROFILE == 'high':
        BATCH_SIZE = 2048 // SCALE_FACTOR
        NUM_WORKERS = max(NUM_WORKERS, min(8, (os.cpu_count() or 8)))
        print("[Throughput] High profile enabled.")
    elif THROUGHPUT_PROFILE == 'cuda_low_ram':
        # Keep memory footprint moderate while maintaining GPU-friendly throughput.
        BATCH_SIZE = 1024 // SCALE_FACTOR
        NUM_WORKERS = min(NUM_WORKERS, max(2, min(6, (os.cpu_count() or 6))))
        DATALOADER_PREFETCH = 2
        print("[Throughput] CUDA low-RAM profile enabled.")

    OBFUSCATION_CONFIG = {
        "len_noise": 0.1,
        "iat_noise": 0.005,
    }
     
    FOCAL_GAMMA = 2.0
    # Stabilize focal alpha on long-tail data:
    # 'none' keeps inverse-frequency as-is;
    # 'sqrt' applies sqrt smoothing; 'log' applies log1p smoothing.
    FOCAL_ALPHA_SMOOTHING = 'sqrt'  # 'none' | 'sqrt' | 'log'
    # Clamp alpha to avoid extreme gradient spikes on ultra-rare classes.
    FOCAL_ALPHA_CLAMP_MIN = 0.1
    FOCAL_ALPHA_CLAMP_MAX = 10.0
    MASK_ENTROPY_REG_ALPHA = 1e-5
    EXPERT_GATE_NOISE_STD = 0.01
    EPSILON = 1e-6 

    ROLLBACK_PATIENCE = NUM_EPOCHS // 10
    EARLY_STOP_PATIENCE = ROLLBACK_PATIENCE + 5
    MIN_LR_FOR_TRAINING = 1e-6
    LOG_FLUSH_EVERY_EPOCH = 1
    EPOCH_GC_CLEANUP = True
    EPOCH_EMPTY_CUDA_CACHE = False
    print(f"Batch size: {BATCH_SIZE}; Learning rate: {LEARNING_RATE}")
    print(f"Backbone mode: {BACKBONE_MODE}")
    print(
        f"Throughput profile: {THROUGHPUT_PROFILE}; workers: {NUM_WORKERS}; "
        f"prefetch: {DATALOADER_PREFETCH}; persistent_workers: {PERSISTENT_WORKERS}"
    )
    print(f"Flow aggregation: {FLOW_AGG_METHOD} (topk={FLOW_TOPK}, soft_temp={FLOW_SOFT_TEMP})")
    print(f"Flow attn config: hidden={FLOW_ATTN_HIDDEN_DIM}, dropout={FLOW_ATTN_DROPOUT}")
    print(
        f"repr_logits_attn config: use_probs={FLOW_REPR_LOGIT_USE_PROBS}, "
        f"use_logit_branch={FLOW_REPR_USE_LOGIT_BRANCH}, "
        f"residual_mean={FLOW_REPR_USE_RESIDUAL_MEAN}, "
        f"logit_residual_baseline={FLOW_REPR_USE_LOGIT_RESIDUAL_BASELINE}, "
        f"logit_residual_init={FLOW_REPR_LOGIT_RESIDUAL_INIT}, "
        f"first_n={FLOW_REPR_FIRST_N_PACKETS}, pool_mode={FLOW_REPR_POOL_MODE}, "
        f"tau={FLOW_REPR_ATTN_TAU}, detach_warmup_epochs={FLOW_REPR_DETACH_WARMUP_EPOCHS}, "
        f"permanent_detach={FLOW_REPR_PERMANENT_DETACH}, "
        f"agg_only_epochs={FLOW_REPR_TRAIN_AGG_ONLY_EPOCHS}, "
        f"gamma_clamp_max={FLOW_REPR_GAMMA_CLAMP_MAX}"
    )
    print(
        f"Flow-centric batching: enabled={ENABLE_FLOW_CENTRIC_BATCHING}, "
        f"flows_per_batch={FLOW_CENTRIC_BATCH_FLOWS}, "
        f"packets_per_flow={FLOW_CENTRIC_PACKETS_PER_FLOW}, "
        f"drop_last={FLOW_CENTRIC_DROP_LAST}, "
        f"low_ram_safe_mode={FLOW_CENTRIC_LOW_RAM_SAFE_MODE}"
    )
    print(
        f"Virtual sink: enabled={ENABLE_VIRTUAL_SINK}, "
        f"name={VIRTUAL_SINK_NAME}"
    )
    print(f"Distilled PTG spec: {DISTILLED_GRAPH_SPEC_PATH}")
    print(
        f"Focal alpha config: smoothing={FOCAL_ALPHA_SMOOTHING}, "
        f"clamp=[{FOCAL_ALPHA_CLAMP_MIN}, {FOCAL_ALPHA_CLAMP_MAX}]"
    )
    print(
        f"Mask entropy alpha: {MASK_ENTROPY_REG_ALPHA}; "
        f"expert gate noise std: {EXPERT_GATE_NOISE_STD}"
    )
    print(
        f"Epoch cleanup: gc={EPOCH_GC_CLEANUP}, "
        f"empty_cuda_cache={EPOCH_EMPTY_CUDA_CACHE}"
    )
     
     
    # dataset_name = 'ISCX-VPN'
    # dataset_name = 'ISCX-TOR-Acctivity'
    # dataset_name = 'ISCX-TOR-Application'
    # dataset_name = 'USTC-TFC2016-Benign'
    # dataset_name = 'dataset_29_d1' 
    # dataset_name = 'dataset_20_d2'
    # dataset_name = 'USTC-TFC2016-Malware'
    dataset_name = 'cstnet_tls_1.3'
    # dataset_name = 'CipherSpectrum'
    root_path = os.path.join('..', 'TrafficData', 'datasets_csv_add2')
    val_test_dir = os.path.join(root_path, 'datasets_split', dataset_name) 
    train_dir = os.path.join(root_path, 'datasets_final')
    vocab_dir = os.path.join(root_path, 'categorical_vocabs')
    config_path = os.path.join('.', 'Data', 'fields_embedding_configs_v1.yaml')
    vocab_path = os.path.join(vocab_dir, dataset_name + '_vocabs.yaml') 
    res_path = os.path.join('..', 'Res')
    # train_set_name = dataset_name + '_chief_block_augmented'
    # train_set_name = dataset_name + '_chief_block_topk_augmented'
    train_set_name = 'train_set'
    val_set_name = 'validation_set' 
    test_set_name = 'test_set'
    # chief_directory = train_dir
    chief_directory = val_test_dir
    val_test_directory = val_test_dir

    upperlayer_dir = os.path.join(root_path, 'datasets_upperlayer', dataset_name) 

    if not FILTER_SHORT_ENTRIES: 
        train_df_path = os.path.join(chief_directory, train_set_name + '.csv') 
        val_df_path = os.path.join(val_test_directory, val_set_name + '.csv')
        test_df_path = os.path.join(val_test_directory, test_set_name + '.csv')
        SOURCE_CSV_PATH = os.path.join(root_path, 'datasets_consolidate', dataset_name + '.csv')
    else: 
        print("USE UPPER FILTER!!!")
        train_df_path = os.path.join(upperlayer_dir, train_set_name + '.csv') 
        val_df_path = os.path.join(upperlayer_dir, val_set_name + '.csv')
        test_df_path = os.path.join(upperlayer_dir, test_set_name + '.csv')

    GLOBAL_CHIEF_SCHEMA = None

    def print_sampling_summary(df: pd.DataFrame, split_name: str):
        print(f"\n[Sampling Summary] {split_name}")
        if df is None or df.empty:
            print(" - Empty dataframe.")
            return
        if 'label' not in df.columns:
            print(" - Missing column: label")
            return
        if 'stream_id' not in df.columns:
            print(" - Missing column: stream_id")
            return

        total_packets = len(df)
        total_flows = df['stream_id'].nunique(dropna=True)
        print(f" - Total packets: {total_packets}")
        print(f" - Total flows: {total_flows}")
        print(f" - Total classes: {df['label'].nunique(dropna=True)}")

        rows = []
        grouped = df.groupby('label', dropna=False)
        for label, g in grouped:
            rows.append({
                'label': label,
                'flows': g['stream_id'].nunique(dropna=True),
                'packets': len(g),
            })

        if not rows:
            print(" - No class rows to display.")
            return

        stat_df = pd.DataFrame(rows).sort_values(by='packets', ascending=False).reset_index(drop=True)
        stat_df['flow_ratio'] = (stat_df['flows'] / max(total_flows, 1)).map(lambda x: f"{x:.4f}")
        stat_df['packet_ratio'] = (stat_df['packets'] / max(total_packets, 1)).map(lambda x: f"{x:.4f}")
        print(stat_df.to_string(index=False))

    def cap_packets_per_flow(df: pd.DataFrame, split_name: str, cap_per_flow: int = None) -> pd.DataFrame:
        if cap_per_flow is None or cap_per_flow <= 0:
            return df
        if df is None or df.empty:
            return df
        if 'stream_id' not in df.columns:
            print(f"[Packet Cap] {split_name}: skip (missing 'stream_id').")
            return df

        before_packets = len(df)
        before_flows = df['stream_id'].nunique(dropna=True)
        shuffled = df.sample(frac=1.0, random_state=SEED).copy()
        shuffled['_flow_pkt_rank'] = shuffled.groupby('stream_id').cumcount()
        capped = shuffled[shuffled['_flow_pkt_rank'] < cap_per_flow].drop(columns=['_flow_pkt_rank'])
        capped = capped.reset_index(drop=True)

        after_packets = len(capped)
        after_flows = capped['stream_id'].nunique(dropna=True)
        print(
            f"[Packet Cap] {split_name}: cap={cap_per_flow}, "
            f"packets {before_packets}->{after_packets}, flows {before_flows}->{after_flows}"
        )
        return capped

    def load_sampled_split(csv_path: str) -> pd.DataFrame:
        if SAMPLING_GRANULARITY == 'flow':
            return stratified_flow_sample_from_csv_stream(
                csv_path=csv_path,
                label_column='label',
                flow_id_column='stream_id',
                proportion=SAMPLING_PROPORTION,
                chunksize=200000,
                random_state=SEED,
                min_flows_per_class=MIN_FLOWS_PER_CLASS,
                prefer_long_flows=PREFER_LONG_FLOWS,
                long_flow_priority_ratio=LONG_FLOW_PRIORITY_RATIO,
                read_csv_kwargs={
                    "dtype": str,
                    "low_memory": False,
                },
            )
        return stratified_hybrid_sample_from_csv_stream(
            csv_path=csv_path,
            label_column='label',
            proportion=SAMPLING_PROPORTION,
            chunksize=200000,
            random_state=SEED,
            read_csv_kwargs={
                "dtype": str,
                "low_memory": False,
            },
        )

    if STRATIFIED_TRAIN_SET: 
        train_df = load_sampled_split(train_df_path)

    else: 
         
        print("\n[1/4] Loading datasets...")
        try:
            train_df = pd.read_csv(train_df_path, dtype=str)
            # val_df = pd.read_csv(val_df_path, dtype=str)
            # test_df = pd.read_csv(test_df_path, dtype=str)
        except FileNotFoundError as e:
            print(f"Error: dataset file not found. Please finish preprocessing first. {e}")
            exit()

    if STRATIFIED_VAL_TEST_SET: 
        val_df = load_sampled_split(val_df_path)

        test_df = load_sampled_split(test_df_path)
    else: 
        try:
            val_df = pd.read_csv(val_df_path, dtype=str)
            test_df = pd.read_csv(test_df_path, dtype=str)
        except FileNotFoundError as e:
            print(f"Error: dataset file not found. Please finish preprocessing first. {e}")
            exit()
        
    print(f" - Train set: {len(train_df)} rows")
    print(f" - Validation set: {len(val_df)} rows")
    print(f" - Test set: {len(test_df)} rows")
    print_sampling_summary(train_df, "Train")
    print_sampling_summary(val_df, "Validation")
    print_sampling_summary(test_df, "Test")

    train_df_full_for_flow_stats = train_df.copy(deep=True) if USE_FLOW_FEATURES_THIS_RUN else None
    val_df_full_for_flow_stats = val_df.copy(deep=True) if USE_FLOW_FEATURES_THIS_RUN else None
    test_df_full_for_flow_stats = test_df.copy(deep=True) if USE_FLOW_FEATURES_THIS_RUN else None

    train_df = cap_packets_per_flow(train_df, "Train", MAX_PACKETS_PER_FLOW_TRAIN)
    val_df = cap_packets_per_flow(val_df, "Validation", MAX_PACKETS_PER_FLOW_EVAL)
    test_df = cap_packets_per_flow(test_df, "Test", MAX_PACKETS_PER_FLOW_EVAL)

    print_sampling_summary(train_df, "Train (after packet cap)")
    print_sampling_summary(val_df, "Validation (after packet cap)")
    print_sampling_summary(test_df, "Test (after packet cap)")

    
    print("\n[3/4] Creating label mapping...")
    labels = train_df['label'].unique() # ?
    label_to_int = {label: i for i, label in enumerate(labels)}
    num_classes = len(labels)

    train_df['label_id'] = train_df['label'].map(label_to_int)


     
    print("\n[2/4] Aligning feature space for validation and test sets...")
    chief_schema = [col for col in train_df.columns if col not in ['label', 'label_id']]

    GLOBAL_CHIEF_SCHEMA = chief_schema
    
     
    val_df_aligned = val_df.reindex(columns=chief_schema, fill_value='0')
    val_df_aligned['label'] = val_df['label']
    
    test_df_aligned = test_df.reindex(columns=chief_schema, fill_value='0')
    test_df_aligned['label'] = test_df['label']
    
    print(" - Feature alignment complete.")
    # ==============================================================
    del val_df, test_df

    val_df_aligned['label_id'] = val_df_aligned['label'].map(label_to_int).fillna(-1).astype(int)   
    test_df_aligned['label_id'] = test_df_aligned['label'].map(label_to_int).fillna(-1).astype(int) 
    test_stream_ids_for_eval = test_df_aligned['stream_id'].astype(str).tolist()
    
    if USE_FLOW_FEATURES_THIS_RUN:
        print("\n[2.5/4] Performing Feature Engineering 5.0 (Correct OPEN_WORLD branching)...")

         
        # flow_feature_names = [
        #     'flow_avg_len', 'flow_std_len', 'flow_pkt_count',
        #     'flow_avg_iat', 'flow_std_iat', 'flow_max_iat',
         
         
        # ]
        def calculate_flow_stats(df: pd.DataFrame, is_train_set: bool = False):
            """
            ?DataFrame ?*? ?

            -  is_train_set=True,  (maps, defaults)
            -  is_train_set=False, ?maps
            - ?flow 
            - 
            """

            print(f"   -> Calculating stats for DataFrame (size: {len(df)})...")

            # ======================
             
            # ======================
            has_ip_len = 'ip.len' in df.columns
            has_stream_id = 'stream_id' in df.columns

            if not (has_ip_len and has_stream_id):
                print("   [Warning] Missing 'ip.len' or 'stream_id'. Skip flow feature stats.")
                 
                if is_train_set:
                    return {}, {}
                else:
                    return {}

            # ======================
             
            # ======================
            if 'ip.len_temp_dec' not in df.columns:
                df['ip.len_temp_dec'] = df['ip.len'].apply(robust_hex_to_int).astype(np.float32)

            if 'stream_id_temp_dec' not in df.columns:
                df['stream_id_temp_dec'] = pd.to_numeric(df['stream_id'], errors='coerce').fillna(-1).astype(np.int64)

            # ======================
             
            # ======================
            has_time = True

            if 'time_temp_dec' in df.columns:
                time_col_used = 'time_temp_dec'
            else:
                candidate_time_cols = [
                    'tcp.options.timestamp',   
                    'frame.time_relative',   
                    'frame.time_epoch',   
                ]
                time_col = None
                for cand in candidate_time_cols:
                    if cand in df.columns:
                        time_col = cand
                        break
                    
                if time_col is None:
                    has_time = False
                    time_col_used = None
                    print("     [Warning] No time column found. Skip IAT/duration features.")
                else:
                    print(f"     -> Using time column '{time_col}' to compute IAT/duration features...")
                    if time_col == 'tcp.options.timestamp':
                        df['time_temp_dec'] = df[time_col].apply(robust_timestamp_to_tsval).astype(np.int64)
                    else:
                        df['time_temp_dec'] = (
                            pd.to_numeric(df[time_col], errors='coerce')
                              .fillna(0)
                              .astype(np.float64)
                        )
                    time_col_used = 'time_temp_dec'

            # ======================
             
            # ======================
            maps = {}

            print("     -> Calculating base length/count features...")
            grouped_len = df.groupby('stream_id_temp_dec')

             
            maps['flow_avg_len']   = grouped_len['ip.len_temp_dec'].mean()
            maps['flow_std_len']   = grouped_len['ip.len_temp_dec'].std().fillna(0)
            maps['flow_pkt_count'] = grouped_len['ip.len_temp_dec'].count()

             
            LARGE_PKT_THRESHOLD = 1400
            large_pkts = df[df['ip.len_temp_dec'] > LARGE_PKT_THRESHOLD]
            base_large_pkt_count = (
                large_pkts
                .groupby('stream_id_temp_dec')
                .size()
                .reindex(maps['flow_pkt_count'].index, fill_value=0)
            )
            print("     -> Calculating large packet ratio...")
            maps['flow_large_pkt_ratio'] = base_large_pkt_count / (maps['flow_pkt_count'] + EPSILON)

            # ======================
             
            # ======================
            if has_time and time_col_used is not None:
                print("     -> Calculating IAT & duration based features...")

                 
                df_sorted = df.sort_values(by=['stream_id_temp_dec', time_col_used]).copy()
                df_sorted['iat_temp'] = (
                    df_sorted
                    .groupby('stream_id_temp_dec')[time_col_used]
                    .diff()
                    .fillna(0)
                )

                 
                grouped_time = df_sorted.groupby('stream_id_temp_dec')

                maps['flow_avg_iat'] = grouped_time['iat_temp'].mean()
                maps['flow_std_iat'] = grouped_time['iat_temp'].std().fillna(0)
                maps['flow_max_iat'] = grouped_time['iat_temp'].max()

                # 4.3 duration_per_pkt
                flow_min_time = grouped_time[time_col_used].min()
                flow_max_time = grouped_time[time_col_used].max()
                base_duration = (flow_max_time - flow_min_time)

                maps['flow_duration_per_pkt'] = base_duration / (maps['flow_pkt_count'] + EPSILON)
            else:
                print("     [Info] Time-based flow features were not computed.")

            # ======================
             
            # ======================
            if is_train_set:
                print("     -> Calculating global defaults (using MEDIAN where appropriate)...")
                defaults = {}

                for f_name, stat_series in maps.items():
                    if ('count' in f_name) or ('ratio' in f_name):
                        default_val = float(stat_series.mean())
                    else:
                        default_val = float(stat_series.median())

                    if np.isnan(default_val) or np.isinf(default_val):
                        default_val = 0.0

                    defaults[f_name] = default_val

                return maps, defaults
            else:
                return maps


         
        
         
        print(" -> [FLOW ENHANCE MODE] Computing flow stats from full sampled flows per split...")

        if train_df_full_for_flow_stats is None:
            train_df_full_for_flow_stats = train_df.copy(deep=True)
        if val_df_full_for_flow_stats is None:
            val_df_full_for_flow_stats = val_df_aligned.copy(deep=True)
        if test_df_full_for_flow_stats is None:
            test_df_full_for_flow_stats = test_df_aligned.copy(deep=True)

        train_maps, train_defaults = calculate_flow_stats(train_df_full_for_flow_stats, is_train_set=True)
        if len(train_maps) == 0:
            raise RuntimeError(
                "[Fatal] Cannot compute flow features. Required columns include "
                "'ip.len' and 'stream_id' (with optional time columns)."
            )

        flow_feature_names = list(train_maps.keys())
        print(" -> Available flow features:", flow_feature_names)

        def build_defaults_from_maps(maps: Dict[str, pd.Series]) -> Dict[str, float]:
            defaults = {}
            for f_name, stat_series in maps.items():
                if ('count' in f_name) or ('ratio' in f_name):
                    default_val = float(stat_series.mean())
                else:
                    default_val = float(stat_series.median())
                if np.isnan(default_val) or np.isinf(default_val):
                    default_val = 0.0
                defaults[f_name] = default_val
            return defaults

        def add_flow_directional_context_features(
            df: pd.DataFrame,
            split_name: str,
        ) -> List[str]:
            """
            Add per-packet flow-context features:
            - direction feature (forward/reverse sign)
            - local iat feature
            """
            if df is None or df.empty:
                return []
            if 'stream_id' not in df.columns or 'ip.len' not in df.columns:
                print(f"   -> [{split_name}] Skip directional context: missing stream_id/ip.len.")
                return []

            if 'stream_id_temp_dec' not in df.columns:
                df['stream_id_temp_dec'] = pd.to_numeric(df['stream_id'], errors='coerce').fillna(-1).astype(np.int64)
            if 'ip.len_temp_dec' not in df.columns:
                df['ip.len_temp_dec'] = df['ip.len'].apply(robust_hex_to_int).astype(np.float32)

            if 'time_temp_dec' in df.columns:
                time_col_used = 'time_temp_dec'
            else:
                time_col_used = None
                for cand in ['tcp.options.timestamp', 'frame.time_relative', 'frame.time_epoch']:
                    if cand in df.columns:
                        if cand == 'tcp.options.timestamp':
                            df['time_temp_dec'] = df[cand].apply(robust_timestamp_to_tsval).astype(np.int64)
                        else:
                            df['time_temp_dec'] = pd.to_numeric(df[cand], errors='coerce').fillna(0).astype(np.float64)
                        time_col_used = 'time_temp_dec'
                        break

            sort_cols = ['stream_id_temp_dec']
            if time_col_used is not None:
                sort_cols.append(time_col_used)

            base_cols = ['stream_id_temp_dec', 'ip.len_temp_dec']
            if time_col_used is not None:
                base_cols.append(time_col_used)
            if 'ip.src' in df.columns and 'ip.dst' in df.columns:
                base_cols.extend(['ip.src', 'ip.dst'])
            elif 'tcp.srcport' in df.columns and 'tcp.dstport' in df.columns:
                base_cols.extend(['tcp.srcport', 'tcp.dstport'])

            work = df[base_cols].copy()
            work['_orig_idx'] = np.arange(len(work), dtype=np.int64)
            work = work.sort_values(sort_cols, kind='mergesort')
            grouped = work.groupby('stream_id_temp_dec', sort=False)

            # Direction sign: +1 means same direction as first packet of this flow.
            if 'ip.src' in work.columns and 'ip.dst' in work.columns:
                src = work['ip.src'].fillna('').astype(str)
                dst = work['ip.dst'].fillna('').astype(str)
                first_src = grouped['ip.src'].transform('first').fillna('').astype(str)
                first_dst = grouped['ip.dst'].transform('first').fillna('').astype(str)
                work['flow_dir_sign'] = np.where((src == first_src) & (dst == first_dst), 1.0, -1.0).astype(np.float32)
            elif 'tcp.srcport' in work.columns and 'tcp.dstport' in work.columns:
                src = work['tcp.srcport'].fillna('').astype(str)
                dst = work['tcp.dstport'].fillna('').astype(str)
                first_src = grouped['tcp.srcport'].transform('first').fillna('').astype(str)
                first_dst = grouped['tcp.dstport'].transform('first').fillna('').astype(str)
                work['flow_dir_sign'] = np.where((src == first_src) & (dst == first_dst), 1.0, -1.0).astype(np.float32)
            else:
                work['flow_dir_sign'] = np.zeros(len(work), dtype=np.float32)

            feature_names = ['flow_dir_sign']

            if time_col_used is not None:
                work['flow_iat_local'] = grouped[time_col_used].diff().fillna(0).astype(np.float32)
                feature_names.append('flow_iat_local')
            else:
                work['flow_iat_local'] = np.zeros(len(work), dtype=np.float32)
                feature_names.append('flow_iat_local')

            work = work.sort_values('_orig_idx')
            for f_name in feature_names:
                df[f_name] = work[f_name].to_numpy()

            print(f"   -> [{split_name}] Added directional context features: {feature_names}")
            return feature_names

        split_full_and_target = [
            ('Train', train_df_full_for_flow_stats, train_df, train_maps, train_defaults),
            ('Validation', val_df_full_for_flow_stats, val_df_aligned, None, None),
            ('Test', test_df_full_for_flow_stats, test_df_aligned, None, None),
        ]

        context_feature_names: List[str] = []

        for split_name, full_df, target_df, known_maps, known_defaults in split_full_and_target:
            if target_df is None or target_df.empty:
                continue

            print(f"   -> Processing {split_name} set...")
            split_maps = known_maps if known_maps is not None else calculate_flow_stats(full_df, is_train_set=False)
            split_defaults = known_defaults if known_defaults is not None else build_defaults_from_maps(split_maps)

            if 'stream_id_temp_dec' not in target_df.columns:
                target_df['stream_id_temp_dec'] = pd.to_numeric(
                    target_df['stream_id'], errors='coerce'
                ).fillna(-1).astype(np.int64)

            for f_name in flow_feature_names:
                feature_map = split_maps.get(f_name)
                if feature_map is None:
                    target_df[f_name] = split_defaults.get(f_name, 0.0)
                else:
                    target_df[f_name] = target_df['stream_id_temp_dec'].map(feature_map).fillna(
                        split_defaults.get(f_name, 0.0)
                    )

            if ENABLE_DIRECTIONAL_FLOW_CONTEXT:
                added_features = add_flow_directional_context_features(
                    target_df,
                    split_name=split_name,
                )
                if added_features:
                    context_feature_names = list(dict.fromkeys(context_feature_names + added_features))

        if ENABLE_DIRECTIONAL_FLOW_CONTEXT and context_feature_names:
            flow_feature_names = list(dict.fromkeys(flow_feature_names + context_feature_names))

        del train_df_full_for_flow_stats, val_df_full_for_flow_stats, test_df_full_for_flow_stats
        gc.collect()

        # d)
        print(" -> Cleaning up temporary decimal columns...")
        for df in [train_df, val_df_aligned, test_df_aligned]:
            if df is None or df.empty:
                continue
            for tmp_col in ['ip.len_temp_dec', 'stream_id_temp_dec', 'time_temp_dec', 'iat_temp']:
                if tmp_col in df.columns: 
                    df.drop(columns=[tmp_col], inplace=True)
        
         
        # print(" -> Final cleanup of *new* flow features (nan/inf/neginf -> 0.0)...")
        # for df in [train_df, val_df_aligned, test_df_aligned]:
        #      if df.empty: continue
        #      for col in flow_feature_names: 
         
        #          col_data_numeric = pd.to_numeric(df[col], errors='coerce')
        #          col_data_np = col_data_numeric.values
        #          col_data_cleaned = np.nan_to_num(col_data_np, nan=0.0, posinf=0.0, neginf=0.0) 
        #          if 'count' in col: df[col] = col_data_cleaned.astype(np.int32)
        #          else: df[col] = col_data_cleaned.astype(np.float32)
                     
        # print(f" -> Feature Engineering 5.0 complete. {len(flow_feature_names)} flow features created.")
        print(" -> Final cleanup of *new* flow features (nan/inf/neginf -> 0.0)...")

        dfs = [
            (train_df,       "train_df"),
            (val_df_aligned, "val_df_aligned"),
            (test_df_aligned,"test_df_aligned"),
        ]

        for df, df_name in dfs:
            if df is None or df.empty:
                continue
            
            for col in flow_feature_names:
                if col not in df.columns:
                     
                    print(f"    [Info] Missing flow feature '{col}' in {df_name}, skipped.")
                    continue
                
                 
                col_data_numeric = pd.to_numeric(df[col], errors='coerce')
                col_data_np = col_data_numeric.values
                col_data_cleaned = np.nan_to_num(
                    col_data_np,
                    nan=0.0,
                    posinf=0.0,
                    neginf=0.0
                )

                if 'count' in col:
                    df[col] = col_data_cleaned.astype(np.int32)
                else:
                    df[col] = col_data_cleaned.astype(np.float32)

        print(f" -> Feature Engineering 5.0 complete. {len(flow_feature_names)} flow features defined for this run.")


     
     
    # print("\n[3/4] Creating label mapping...")
    # labels = train_df['label'].unique() # ?
    # label_to_int = {label: i for i, label in enumerate(labels)}
    # num_classes = len(labels)

    # train_df['label_id'] = train_df['label'].map(label_to_int)
     
    # test_df_aligned['label_id'] = test_df_aligned['label'].map(label_to_int).fillna(-1).astype(int) 
    

     
    print("\n[4/4] Creating GNN Datasets and DataLoaders...")
    
     
    train_dataset = GNNTrafficDataset(train_df, config_path, vocab_path, use_flow_features=USE_FLOW_FEATURES_THIS_RUN, enabled_layers=ABLATION_LAYERS, 
                                      backbone_mode=BACKBONE_MODE,
                                      use_ip_address=USE_IP_ADDRESS_THIS_RUN, use_mac_address=USE_MAC_ADDRESS_THIS_RUN, use_port=USE_PORT_THIS_RUN,
                                      enable_virtual_sink=ENABLE_VIRTUAL_SINK, virtual_sink_name=VIRTUAL_SINK_NAME,
                                      obfuscation_config=None,
                                      distilled_graph_spec_path=DISTILLED_GRAPH_SPEC_PATH)
    val_dataset = GNNTrafficDataset(val_df_aligned, config_path, vocab_path, use_flow_features=USE_FLOW_FEATURES_THIS_RUN, enabled_layers=ABLATION_LAYERS, 
                                    backbone_mode=BACKBONE_MODE,
                                    use_ip_address=USE_IP_ADDRESS_THIS_RUN, use_mac_address=USE_MAC_ADDRESS_THIS_RUN, use_port=USE_PORT_THIS_RUN,
                                    enable_virtual_sink=ENABLE_VIRTUAL_SINK, virtual_sink_name=VIRTUAL_SINK_NAME,
                                    obfuscation_config=None,
                                    distilled_graph_spec_path=DISTILLED_GRAPH_SPEC_PATH)
    test_dataset = GNNTrafficDataset(test_df_aligned, config_path, vocab_path, use_flow_features=USE_FLOW_FEATURES_THIS_RUN, enabled_layers=ABLATION_LAYERS, 
                                     backbone_mode=BACKBONE_MODE,
                                     use_ip_address=USE_IP_ADDRESS_THIS_RUN, use_mac_address=USE_MAC_ADDRESS_THIS_RUN, use_port=USE_PORT_THIS_RUN,
                                     enable_virtual_sink=ENABLE_VIRTUAL_SINK, virtual_sink_name=VIRTUAL_SINK_NAME,
                                     obfuscation_config=None,
                                     distilled_graph_spec_path=DISTILLED_GRAPH_SPEC_PATH)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nUsing device: {device}")
    amp_dtype = torch.float16 if AMP_DTYPE_STR.lower() == 'fp16' else torch.bfloat16
    use_amp_this_run = bool(USE_AMP and device.type == 'cuda')
    print(f"AMP enabled: {use_amp_this_run} (dtype={AMP_DTYPE_STR})")

     
    
    print("Calculating static class weights (alpha) for FocalLoss...")
    if TRAIN_TARGET == 'flow' and 'stream_id' in train_df.columns:
        # Align class weights with flow-level supervision target.
        flow_label_df = train_df[['stream_id', 'label_id']].drop_duplicates(subset=['stream_id'])
        class_counts_series = flow_label_df['label_id'].value_counts().sort_index()
        alpha_count_level = "flow"
    else:
        # Packet-level fallback.
        class_counts_series = train_df['label_id'].value_counts().sort_index()
        alpha_count_level = "packet"

    class_counts_series = class_counts_series.reindex(range(num_classes), fill_value=0)
    class_counts_np = class_counts_series.to_numpy(dtype=np.int64)
    class_counts_np[class_counts_np <= 0] = 1

    class_weights = torch.tensor(class_counts_np, dtype=torch.float)
    total_samples = class_weights.sum()
    raw_alpha = total_samples / (num_classes * class_weights)

    if FOCAL_ALPHA_SMOOTHING == 'sqrt':
        class_weights = torch.sqrt(raw_alpha)
    elif FOCAL_ALPHA_SMOOTHING == 'log':
        class_weights = torch.log1p(raw_alpha)
    elif FOCAL_ALPHA_SMOOTHING == 'none':
        class_weights = raw_alpha
    else:
        raise ValueError(f"Unsupported FOCAL_ALPHA_SMOOTHING: {FOCAL_ALPHA_SMOOTHING}")

    if FOCAL_ALPHA_CLAMP_MIN is not None or FOCAL_ALPHA_CLAMP_MAX is not None:
        cmin = float(FOCAL_ALPHA_CLAMP_MIN) if FOCAL_ALPHA_CLAMP_MIN is not None else None
        cmax = float(FOCAL_ALPHA_CLAMP_MAX) if FOCAL_ALPHA_CLAMP_MAX is not None else None
        if cmin is not None and cmax is not None:
            class_weights = torch.clamp(class_weights, min=cmin, max=cmax)
        elif cmin is not None:
            class_weights = torch.clamp(class_weights, min=cmin)
        elif cmax is not None:
            class_weights = torch.clamp(class_weights, max=cmax)
    
     
    alpha_weights = class_weights.to(device)
    
    print(f" -> Focal alpha count level: {alpha_count_level}")
    print(f" -> Focal alpha class counts: {class_counts_np.tolist()}")
    print(f" -> Focal raw alpha (inv-freq): {raw_alpha.numpy().round(3).tolist()}")
    print(f" -> FocalLoss Alpha (weights): {alpha_weights.cpu().numpy().round(2)}")

     
    loss_fn = FocalLoss(alpha=alpha_weights, gamma=FOCAL_GAMMA).to(device)

     
    # dynamic_weights = torch.ones(num_classes, dtype=torch.float).to(device)
    
    # =====================================================================
    if not DIAGNOSE: 
        del train_df, val_df_aligned, test_df_aligned
        gc.collect()
    
    expert_graph_info = train_dataset.expert_graphs

     
    # node_fields_for_model = train_dataset.node_fields
    # print(f" - Model will be built for {len(node_fields_for_model)} nodes.")

    g = torch.Generator()
    g.manual_seed(SEED)

     
    if ENABLE_FLOW_CENTRIC_BATCHING and TRAIN_TARGET == 'flow':
        fc_workers = NUM_WORKERS
        fc_pin_memory = True
        fc_persistent_workers = (PERSISTENT_WORKERS and NUM_WORKERS > 0)
        fc_prefetch = DATALOADER_PREFETCH
        if FLOW_CENTRIC_LOW_RAM_SAFE_MODE:
            # Windows + multiprocessing shared-memory path is prone to error 1455
            # under large batches. Keep workers conservative in flow-centric mode.
            fc_workers = 0 if os.name == 'nt' else min(NUM_WORKERS, 2)
            fc_pin_memory = False
            fc_persistent_workers = False
            fc_prefetch = 1

        train_batch_sampler = FlowCentricBatchSampler(
            flow_ids=train_dataset.flow_ids,
            packets_per_flow=FLOW_CENTRIC_PACKETS_PER_FLOW,
            flows_per_batch=FLOW_CENTRIC_BATCH_FLOWS,
            shuffle_flows=True,
            drop_last=FLOW_CENTRIC_DROP_LAST,
        )
        val_batch_sampler = FlowCentricBatchSampler(
            flow_ids=val_dataset.flow_ids,
            packets_per_flow=FLOW_CENTRIC_PACKETS_PER_FLOW,
            flows_per_batch=FLOW_CENTRIC_BATCH_FLOWS,
            shuffle_flows=False,
            drop_last=False,
        )
        test_batch_sampler = FlowCentricBatchSampler(
            flow_ids=test_dataset.flow_ids,
            packets_per_flow=FLOW_CENTRIC_PACKETS_PER_FLOW,
            flows_per_batch=FLOW_CENTRIC_BATCH_FLOWS,
            shuffle_flows=False,
            drop_last=False,
        )
        print(
            f"Flow-centric loaders: train_steps={len(train_batch_sampler)}, "
            f"val_steps={len(val_batch_sampler)}, test_steps={len(test_batch_sampler)}; "
            f"workers={fc_workers}, pin_memory={fc_pin_memory}, "
            f"persistent_workers={fc_persistent_workers}, prefetch={fc_prefetch}"
        )
        flow_loader_kwargs = {
            "num_workers": fc_workers,
            "pin_memory": fc_pin_memory,
            "worker_init_fn": seed_worker,
            "persistent_workers": fc_persistent_workers,
            "collate_fn": train_dataset.collate_from_index,
        }
        if fc_workers > 0:
            flow_loader_kwargs["prefetch_factor"] = fc_prefetch
        train_loader = DataLoader(
            train_dataset,
            batch_sampler=train_batch_sampler,
            **flow_loader_kwargs,
        )
        flow_loader_kwargs_val = dict(flow_loader_kwargs)
        flow_loader_kwargs_val["collate_fn"] = val_dataset.collate_from_index
        val_loader = DataLoader(
            val_dataset,
            batch_sampler=val_batch_sampler,
            **flow_loader_kwargs_val,
        )
        flow_loader_kwargs_test = dict(flow_loader_kwargs)
        flow_loader_kwargs_test["collate_fn"] = test_dataset.collate_from_index
        test_loader = DataLoader(
            test_dataset,
            batch_sampler=test_batch_sampler,
            **flow_loader_kwargs_test,
        )
    else:
        train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, 
                                num_workers=NUM_WORKERS, pin_memory=True, worker_init_fn=seed_worker, generator=g, 
                                drop_last=True, 
                                persistent_workers=(PERSISTENT_WORKERS and NUM_WORKERS > 0),
                                prefetch_factor=DATALOADER_PREFETCH, 
                                collate_fn=train_dataset.collate_from_index,
                                )
        val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, 
                                num_workers=NUM_WORKERS, pin_memory=True, worker_init_fn=seed_worker, 
                                persistent_workers=(PERSISTENT_WORKERS and NUM_WORKERS > 0),
                                prefetch_factor=DATALOADER_PREFETCH, 
                                collate_fn=val_dataset.collate_from_index,
                                )
        test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True, worker_init_fn=seed_worker, 
                                persistent_workers=(PERSISTENT_WORKERS and NUM_WORKERS > 0),
                                prefetch_factor=DATALOADER_PREFETCH, 
                                collate_fn=test_dataset.collate_from_index,
                                )
    
     
    
    
    field_embedder = FieldEmbedding(config_path, vocab_path)
    field_embedder.to(device)

    pta_model = HierarchicalMoE(
        config_path=config_path,
        vocab_path=vocab_path,
        num_classes=num_classes,
        expert_graph_info=expert_graph_info,   
        use_flow_features=USE_FLOW_FEATURES_THIS_RUN,
        num_flow_features=len(train_dataset.flow_feature_names) if USE_FLOW_FEATURES_THIS_RUN else 0,
        hidden_dim=GNN_HIDDEN_DIM, 
        dropout_rate=DROPOUT_RATE,
        expert_gate_noise_std=EXPERT_GATE_NOISE_STD,
    )#.to(device)

     
     
    if torch.cuda.is_available():
        print("Setting torch.set_float32_matmul_precision('high')")
        torch.set_float32_matmul_precision('high')  

    pta_model.to(device)
    flow_packet_weighter = None
    if TRAIN_TARGET == 'flow' and FLOW_AGG_METHOD == 'learned_attn_logits':
        flow_packet_weighter = FlowLogitAttentionPool(
            num_classes=num_classes,
            hidden_dim=FLOW_ATTN_HIDDEN_DIM,
            dropout=FLOW_ATTN_DROPOUT,
        ).to(device)
        print("Flow learnable aggregator enabled (learned_attn_logits).")
    elif TRAIN_TARGET == 'flow' and FLOW_AGG_METHOD == 'repr_logits_attn':
        flow_packet_weighter = FlowReprLogitAggregator(
            repr_dim=GNN_HIDDEN_DIM,
            num_classes=num_classes,
            hidden_dim=FLOW_ATTN_HIDDEN_DIM,
            dropout=FLOW_ATTN_DROPOUT,
            use_prob_input=FLOW_REPR_LOGIT_USE_PROBS,
            use_logit_branch=FLOW_REPR_USE_LOGIT_BRANCH,
            attn_temperature=FLOW_REPR_ATTN_TAU,
            use_residual_mean=FLOW_REPR_USE_RESIDUAL_MEAN,
            use_logit_residual_baseline=FLOW_REPR_USE_LOGIT_RESIDUAL_BASELINE,
            logit_residual_init=FLOW_REPR_LOGIT_RESIDUAL_INIT,
            first_n_packets=FLOW_REPR_FIRST_N_PACKETS,
            pool_mode=FLOW_REPR_POOL_MODE,
        ).to(device)
        print("Flow learnable aggregator enabled (repr_logits_attn).")

    optim_params = list(pta_model.parameters())
    if flow_packet_weighter is not None:
        optim_params += list(flow_packet_weighter.parameters())
    optimizer = optim.AdamW(optim_params, lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY) # add weight_decay
    scaler = torch.cuda.amp.GradScaler(enabled=use_amp_this_run)

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode='max',   
        factor=0.2,   
        patience=4,   
        verbose=True,   
        min_lr=1e-6   
    )

     
    # dynamic_weights = torch.ones(num_classes, dtype=torch.float).to(device)

     
    if not DIAGNOSE: 
        training_results = []
        best_f1 = 0.0
        best_val_f1_macro = 0.0 
        epochs_since_best = 0 
        epochs_needs_early_stop = 0
        best_epoch = -1
        best_model_state = None
        best_flow_weighter_state = None
        for epoch in range(NUM_EPOCHS): 
            if stop_training:
                print("Learning rate too low. Stopping training early.")
                break

            print(f"\n--- Epoch {epoch+1}/{NUM_EPOCHS} ---")
            agg_only_mode = (
                TRAIN_TARGET == 'flow'
                and FLOW_AGG_METHOD == 'repr_logits_attn'
                and epoch < max(0, int(FLOW_REPR_TRAIN_AGG_ONLY_EPOCHS))
            )
            if agg_only_mode:
                # Freeze backbone and only train flow aggregator for a few warmup epochs.
                set_module_requires_grad(pta_model, False)
                if flow_packet_weighter is not None:
                    set_module_requires_grad(flow_packet_weighter, True)
                print("   -> Aggregator-only warmup active: backbone frozen.")
            else:
                set_module_requires_grad(pta_model, True)
                if flow_packet_weighter is not None:
                    set_module_requires_grad(flow_packet_weighter, True)

            train_metrics, _ = train_one_epoch(pta_model, train_loader, # loss_fn, 
                                               optimizer, # scheduler, 
                                               device, num_classes, loss_fn,
                                               alpha=MASK_ENTROPY_REG_ALPHA,
                                               train_target=TRAIN_TARGET,
                                               flow_agg_method=FLOW_AGG_METHOD,
                                               flow_topk=FLOW_TOPK,
                                               flow_soft_temp=FLOW_SOFT_TEMP,
                                               flow_packet_weighter=flow_packet_weighter,
                                               flow_loss_use_packet_aux=FLOW_LOSS_USE_PACKET_AUX,
                                               flow_packet_aux_weight=FLOW_PACKET_AUX_WEIGHT,
                                               current_epoch=epoch,
                                               repr_detach_warmup_epochs=FLOW_REPR_DETACH_WARMUP_EPOCHS,
                                               repr_permanent_detach=FLOW_REPR_PERMANENT_DETACH,
                                               flow_repr_gamma_clamp_max=FLOW_REPR_GAMMA_CLAMP_MAX,
                                               collect_dual_level_metrics=ENABLE_DUAL_LEVEL_METRICS,
                                               use_amp=use_amp_this_run,
                                               amp_dtype=amp_dtype,
                                               scaler=scaler)
                                            #    dynamic_weights=dynamic_weights)
            # val_metrics, _, val_per_class_f1 = evaluate(pta_model, val_loader, # loss_fn, 
            #                           device, num_classes)
            val_metrics, _ = evaluate(pta_model, val_loader, # loss_fn, 
                                      device, num_classes, loss_fn,
                                      eval_target=TRAIN_TARGET,
                                      flow_agg_method=FLOW_AGG_METHOD,
                                      flow_topk=FLOW_TOPK,
                                      flow_soft_temp=FLOW_SOFT_TEMP,
                                      flow_packet_weighter=flow_packet_weighter,
                                      collect_dual_level_metrics=ENABLE_DUAL_LEVEL_METRICS,
                                      use_amp=use_amp_this_run,
                                      amp_dtype=amp_dtype)
            
            # beta = 2.0 
            # new_weights = (1.0 - val_per_class_f1)**beta
             
            # new_weights = new_weights / new_weights.mean() 
            # dynamic_weights = new_weights.to(device)

             
             
             

             
             
             
            # momentum = 0.9 
             

            # updated_weights = (momentum * dynamic_weights_cpu) + ((1 - momentum) * new_weights)

             
            # dynamic_weights = updated_weights.to(device)
             

            print(f"Epoch {epoch+1} Summary:")
            print(f"  Train Loss: {train_metrics['loss']:.4f} | Train Acc: {train_metrics['accuracy']:.4f} | Train F1 (macro): {train_metrics['f1_macro']:.4f}")
            print(f"  Val Loss: {val_metrics['loss']:.4f} | Val Acc: {val_metrics['accuracy']:.4f} | Val F1 (macro): {val_metrics['f1_macro']:.4f}")
            if ENABLE_DUAL_LEVEL_METRICS:
                print(
                    f"  Train Packet F1: {train_metrics['packet_f1_macro']:.4f} | "
                    f"Train Flow F1: {train_metrics['flow_f1_macro']:.4f} | "
                    f"Target: {TRAIN_TARGET}"
                )
                print(
                    f"  Val   Packet F1: {val_metrics['packet_f1_macro']:.4f} | "
                    f"Val   Flow F1: {val_metrics['flow_f1_macro']:.4f}"
                )

            current_lr = optimizer.param_groups[0]['lr']
            print(f"Epoch {epoch+1} Summary (Current LR: {current_lr:.1e}):")
            # print(f"Epoch {epoch+1} Summary (LR: {scheduler.get_last_lr()[0]:.1e}):")

            training_results.append({
                'epoch': epoch + 1,
                'train_loss': train_metrics['loss'],
                'train_acc': train_metrics['accuracy'], 
                'train_recall_macro': train_metrics['recall_macro'], 
                'train_precision_macro': train_metrics['precision_macro'], 
                'train_f1_macro': train_metrics['f1_macro'], 
                'train_recall_weighted': train_metrics['recall_weighted'], 
                'train_precision_weighted': train_metrics['precision_weighted'], 
                'train_f1_weighted': train_metrics['f1_weighted'], 
                'train_packet_acc': train_metrics['packet_accuracy'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_packet_f1_macro': train_metrics['packet_f1_macro'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_packet_f1_weighted': train_metrics['packet_f1_weighted'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_packet_samples': train_metrics['packet_samples'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_flow_acc': train_metrics['flow_accuracy'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_flow_f1_macro': train_metrics['flow_f1_macro'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_flow_f1_weighted': train_metrics['flow_f1_weighted'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'train_flow_samples': train_metrics['flow_samples'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_loss': val_metrics['loss'],
                'val_acc': val_metrics['accuracy'], 
                'val_recall_macro': val_metrics['recall_macro'], 
                'val_precision_macro': val_metrics['precision_macro'], 
                'val_f1_macro': val_metrics['f1_macro'], 
                'val_recall_weighted': val_metrics['recall_weighted'], 
                'val_precision_weighted': val_metrics['precision_weighted'], 
                'val_f1_weighted': val_metrics['f1_weighted'], 
                'val_packet_acc': val_metrics['packet_accuracy'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_packet_f1_macro': val_metrics['packet_f1_macro'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_packet_f1_weighted': val_metrics['packet_f1_weighted'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_packet_samples': val_metrics['packet_samples'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_flow_acc': val_metrics['flow_accuracy'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_flow_f1_macro': val_metrics['flow_f1_macro'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_flow_f1_weighted': val_metrics['flow_f1_weighted'] if ENABLE_DUAL_LEVEL_METRICS else None,
                'val_flow_samples': val_metrics['flow_samples'] if ENABLE_DUAL_LEVEL_METRICS else None,
            })
            if (epoch + 1) % LOG_FLUSH_EVERY_EPOCH == 0:
                try:
                    pd.DataFrame(training_results).to_csv(
                        os.path.join(res_path, dataset_name + '_' + train_set_name + '_training_log.csv'),
                        index=False
                    )
                except Exception as e:
                    print(f"[Warning] Failed to flush training log at epoch {epoch+1}: {e}")

            current_val_f1_macro = val_metrics['f1_macro']
            scheduler.step(current_val_f1_macro)

            if current_val_f1_macro > best_val_f1_macro:
                 
                print(f" -> Validation Macro F1 improved from {best_val_f1_macro:.4f} to {current_val_f1_macro:.4f}. Saving state...")
                best_val_f1_macro = current_val_f1_macro
                best_epoch = epoch + 1
                 
                best_model_state = copy.deepcopy(pta_model.state_dict())
                if flow_packet_weighter is not None:
                    best_flow_weighter_state = copy.deepcopy(flow_packet_weighter.state_dict())
                torch.save(pta_model.state_dict(), os.path.join(res_path, dataset_name + '_' + train_set_name + '_best_model.pth'))
                if flow_packet_weighter is not None:
                    torch.save(
                        flow_packet_weighter.state_dict(),
                        os.path.join(res_path, dataset_name + '_' + train_set_name + '_best_flow_aggregator.pth')
                    )
                epochs_since_best = 0
                epochs_needs_early_stop = 0
            else:
                 
                epochs_since_best += 1
                epochs_needs_early_stop += 1
                print(f" -> Validation Macro F1 did not improve for {epochs_since_best} epoch(s). Best was {best_val_f1_macro:.4f} at epoch {best_epoch}.")

                if epochs_since_best >= ROLLBACK_PATIENCE:
                    print(f"\n!!! Performance has not improved for {ROLLBACK_PATIENCE} epochs. Rolling back to best model from epoch {best_epoch}. !!!")

                    if best_model_state:
                         
                        pta_model.load_state_dict(best_model_state)
                        if flow_packet_weighter is not None and best_flow_weighter_state is not None:
                            flow_packet_weighter.load_state_dict(best_flow_weighter_state)

                         
                        # print("   -> Aggressively reducing current learning rate by half...")
                        # new_lr = optimizer.param_groups[0]['lr'] * 0.5
                        # for param_group in optimizer.param_groups:
                        #     param_group['lr'] = new_lr

                         
                        epochs_since_best = 0

                         
                        # if new_lr < MIN_LR_FOR_TRAINING:
                        #     print(f"   -> Learning rate ({new_lr:.1e}) has fallen below minimum. Triggering final early stop.")
                         
                    else:
                        print("   -> Warning: No best model state found. Stopping training.")
                        break   
                 
                current_lr = optimizer.param_groups[0]['lr']
                if epochs_needs_early_stop >= EARLY_STOP_PATIENCE: 
                    print(f"Model's performance has not involved in {epochs_needs_early_stop} epoches. Triggering final early stop.")
                    stop_training = True   

            if EPOCH_GC_CLEANUP:
                gc.collect()
                if EPOCH_EMPTY_CUDA_CACHE and torch.cuda.is_available():
                    torch.cuda.empty_cache()

        print("\nTraining complete!")

         
        print("\n" + "="*50)
        print("###   Learned Feature Importance Report   ###")

        importance_reports_dict = pta_model.get_feature_importance()

         
        # print(importance_report.to_string())

         
        # importance_report.to_csv(os.path.join(res_path,train_set_name + '_feature_importance_report.csv'), index=False)
        # print("\nFeature importance report saved to 'feature_importance_report.csv'")
        # print("="*50)

        all_reports_list = []
        for expert_name, expert_df in importance_reports_dict.items():
            print(f"\n--- Importance for Expert: '{expert_name}' ---")
             
            print(expert_df.to_string())
        
             
            expert_df_with_name = expert_df.copy()
            expert_df_with_name['expert_name'] = expert_name
            all_reports_list.append(expert_df_with_name)           
         
        combined_report_df = pd.concat(all_reports_list).reset_index(drop=True)

         
        report_output_path = os.path.join(res_path, dataset_name + '_' + train_set_name + '_feature_importance_report.csv')
        combined_report_df.to_csv(report_output_path, index=False)

        print(f"\nCombined feature importance report saved to: {report_output_path}")
        print("="*50)

         
        print("\n" + "="*50)
        print("###   Learned Expert Layer Importance Report (Macro)   ###")
        
         
        try:
            expert_layer_report = pta_model.get_expert_importance()
            
             
            print(expert_layer_report.to_string())
            
             
            expert_report_path = os.path.join(res_path, dataset_name + '_' + train_set_name + '_lastbatch_expert_layer_importance.csv')
            expert_layer_report.to_csv(expert_report_path, index=False)
            print(f"\nExpert layer importance saved to: {expert_report_path}")
        except Exception as e:
            print(f"Warning: Could not generate expert importance report. Error: {e}")
        
        print("="*50)
        # ============================================================================

         
        pta_model.load_state_dict(torch.load(os.path.join(res_path, dataset_name + '_' + train_set_name + '_best_model.pth')))
        pta_model.to(device)
        if flow_packet_weighter is not None:
            agg_path = os.path.join(res_path, dataset_name + '_' + train_set_name + '_best_flow_aggregator.pth')
            if os.path.exists(agg_path):
                flow_packet_weighter.load_state_dict(torch.load(agg_path, map_location=device))
                flow_packet_weighter.to(device)
            else:
                print(f"Warning: flow aggregator checkpoint not found: {agg_path}")
        test_metrics, test_confusion_matrix = evaluate(
            pta_model, test_loader, device, num_classes, loss_fn,
            eval_target=TRAIN_TARGET,
            flow_agg_method=FLOW_AGG_METHOD,
            flow_topk=FLOW_TOPK,
            flow_soft_temp=FLOW_SOFT_TEMP,
            flow_packet_weighter=flow_packet_weighter,
            use_amp=use_amp_this_run,
            amp_dtype=amp_dtype
        )
        print(f"\nFinal Test Performance:")
        print(f"  Test Loss: {test_metrics['loss']:.4f} | Test Acc: {test_metrics['accuracy']:.4f} | Test F1 (Macro): {test_metrics['f1_macro']:.4f}")
        flow_metrics = None
        flow_confusion_matrix = None
        if ENABLE_FLOW_AGG_EVAL and TRAIN_TARGET == 'packet':
            print("\n[Flow Aggregation Eval] Building flow-level predictions from packet logits...")
            packet_logits, packet_labels = collect_packet_logits_labels(pta_model, test_loader, device)
            flow_metrics, flow_confusion_matrix = evaluate_flow_aggregation_from_packet_logits(
                packet_logits=packet_logits,
                packet_labels=packet_labels,
                flow_ids=test_stream_ids_for_eval,
                num_classes=num_classes,
                use_prob_mean=FLOW_AGG_USE_PROB_MEAN,
            )
            print(
                f"  Flow Acc: {flow_metrics['accuracy']:.4f} | "
                f"Flow F1 (Macro): {flow_metrics['f1_macro']:.4f} | "
                f"Flows: {flow_metrics['num_flows']} | "
                f"Inconsistent flows: {flow_metrics['inconsistent_flows']}"
            )

         
        print("\nSaving confusion matrix...")

         
         
        int_to_label = {i: label for label, i in label_to_int.items()}
        class_names = [int_to_label[i] for i in range(num_classes)]

         
        confusion_matrix_df = pd.DataFrame(
            test_confusion_matrix.cpu().numpy(),   
            index=class_names,
            columns=class_names
        )

         
        cm_output_path = os.path.join(res_path, dataset_name + '_' + train_set_name + '_final_test_confusion_matrix.csv')
        confusion_matrix_df.to_csv(cm_output_path)

        print(f"Confusion matrix saved to: {cm_output_path}")
        if ENABLE_FLOW_AGG_EVAL and TRAIN_TARGET == 'packet' and flow_confusion_matrix is not None:
            flow_confusion_matrix_df = pd.DataFrame(
                flow_confusion_matrix.cpu().numpy(),
                index=class_names,
                columns=class_names
            )
            flow_cm_output_path = os.path.join(
                res_path, dataset_name + '_' + train_set_name + '_final_test_flow_confusion_matrix.csv'
            )
            flow_confusion_matrix_df.to_csv(flow_cm_output_path)
            print(f"Flow confusion matrix saved to: {flow_cm_output_path}")

        training_results.append({
            'epoch': 'final_test',
            'train_loss': None,
            'train_acc': None, 
            'train_recall_macro': None, 
            'train_precision_macro': None, 
            'train_f1_macro': None, 
            'train_recall_weighted': None, 
            'train_precision_weighted': None, 
            'train_f1_weighted': None, 
            'val_loss': test_metrics['loss'],
            'val_acc': test_metrics['accuracy'], 
            'val_recall_macro': test_metrics['recall_macro'], 
            'val_precision_macro': test_metrics['precision_macro'], 
            'val_f1_macro': test_metrics['f1_macro'], 
            'val_recall_weighted': test_metrics['recall_weighted'], 
            'val_precision_weighted': test_metrics['precision_weighted'], 
            'val_f1_weighted': test_metrics['f1_weighted'],
            'flow_acc': (
                flow_metrics['accuracy'] if flow_metrics is not None
                else (test_metrics['accuracy'] if TRAIN_TARGET == 'flow' else None)
            ),
            'flow_f1_macro': (
                flow_metrics['f1_macro'] if flow_metrics is not None
                else (test_metrics['f1_macro'] if TRAIN_TARGET == 'flow' else None)
            ),
            'flow_num_flows': (flow_metrics['num_flows'] if flow_metrics is not None else None),
            'flow_inconsistent_flows': (flow_metrics['inconsistent_flows'] if flow_metrics is not None else None),
        })

        results_df = pd.DataFrame(training_results)
        results_df.to_csv(os.path.join(res_path,dataset_name + '_' + train_set_name + '_training_log.csv'), index=False)
        print(f"\nTraining log saved to {train_set_name}_training_log.csv")

        print("\nComputing dataset-level expert importance...")

        expected_expert_weights = compute_dataset_expert_importance(
            pta_model,
            test_loader,   
            device
        )

        print("Expected expert weights:", expected_expert_weights.numpy())

        expert_names = pta_model.gnn_expert_names.copy()
        if pta_model.use_flow_features:
            expert_names.append("Flow_Features_Block")

        df_expert = pd.DataFrame({
            "expert_name": expert_names,
            "importance_score": expected_expert_weights.numpy()
        })

        expert_csv_path = os.path.join(
            res_path,
            dataset_name + '_' + train_set_name + '_expert_layer_importance.csv'
        )

        df_expert.to_csv(expert_csv_path, index=False)

        print(f"Expert importance saved to: {expert_csv_path}")

    elif DIAGNOSE:

        print("\n==============================")
        print("  Diagnose Eval-Only Mode ")
        print("==============================\n")

        best_model_path = os.path.join(
            res_path,
            dataset_name + '_' + train_set_name + '_best_model.pth'
        )

        if not os.path.exists(best_model_path):
            print(f"Error: saved model file not found: {best_model_path}")
            exit()

        print("Loading saved model...")
        pta_model.load_state_dict(torch.load(best_model_path, map_location=device))
        pta_model.to(device)
        if flow_packet_weighter is not None:
            agg_path = os.path.join(res_path, dataset_name + '_' + train_set_name + '_best_flow_aggregator.pth')
            if os.path.exists(agg_path):
                flow_packet_weighter.load_state_dict(torch.load(agg_path, map_location=device))
                flow_packet_weighter.to(device)
            else:
                print(f"Warning: flow aggregator checkpoint not found: {agg_path}")
        pta_model.eval()
        print("Model loaded successfully.\n")

        test_metrics, test_confusion_matrix = evaluate(
            pta_model,
            test_loader,
            device,
            num_classes,
            loss_fn,
            eval_target=TRAIN_TARGET,
            flow_agg_method=FLOW_AGG_METHOD,
            flow_topk=FLOW_TOPK,
            flow_soft_temp=FLOW_SOFT_TEMP,
            flow_packet_weighter=flow_packet_weighter,
            use_amp=use_amp_this_run,
            amp_dtype=amp_dtype
        )
        print("Final Test (Eval-Only):")
        print(f"  Test Loss: {test_metrics['loss']:.4f}")
        print(f"  Test Acc: {test_metrics['accuracy']:.4f}")
        print(f"  Test F1 (Macro): {test_metrics['f1_macro']:.4f}")

        int_to_label = {i: label for label, i in label_to_int.items()}
        class_names = [int_to_label[i] for i in range(num_classes)]
        confusion_matrix_df = pd.DataFrame(
            test_confusion_matrix.cpu().numpy(),
            index=class_names,
            columns=class_names
        )
        cm_output_path = os.path.join(
            res_path,
            dataset_name + '_' + train_set_name + '_diagnose_test_confusion_matrix.csv'
        )
        confusion_matrix_df.to_csv(cm_output_path)
        print(f"Confusion matrix saved to: {cm_output_path}")

        flow_metrics = None
        if ENABLE_FLOW_AGG_EVAL and TRAIN_TARGET == 'packet':
            packet_logits, packet_labels = collect_packet_logits_labels(pta_model, test_loader, device)
            flow_metrics, flow_confusion_matrix = evaluate_flow_aggregation_from_packet_logits(
                packet_logits=packet_logits,
                packet_labels=packet_labels,
                flow_ids=test_stream_ids_for_eval,
                num_classes=num_classes,
                use_prob_mean=FLOW_AGG_USE_PROB_MEAN,
            )
            print("Flow Aggregation (Eval-Only):")
            print(f"  Flow Acc: {flow_metrics['accuracy']:.4f}")
            print(f"  Flow F1 (Macro): {flow_metrics['f1_macro']:.4f}")
            print(f"  Num flows: {flow_metrics['num_flows']}")
            print(f"  Inconsistent flows: {flow_metrics['inconsistent_flows']}")

            flow_confusion_matrix_df = pd.DataFrame(
                flow_confusion_matrix.cpu().numpy(),
                index=class_names,
                columns=class_names
            )
            flow_cm_output_path = os.path.join(
                res_path,
                dataset_name + '_' + train_set_name + '_diagnose_test_flow_confusion_matrix.csv'
            )
            flow_confusion_matrix_df.to_csv(flow_cm_output_path)
            print(f"Flow confusion matrix saved to: {flow_cm_output_path}")

        diagnose_summary = {
            'test_loss': test_metrics['loss'],
            'test_acc': test_metrics['accuracy'],
            'test_f1_macro': test_metrics['f1_macro'],
            'test_precision_macro': test_metrics['precision_macro'],
            'test_recall_macro': test_metrics['recall_macro'],
            'flow_acc': (flow_metrics['accuracy'] if flow_metrics is not None else None),
            'flow_f1_macro': (flow_metrics['f1_macro'] if flow_metrics is not None else None),
            'flow_num_flows': (flow_metrics['num_flows'] if flow_metrics is not None else None),
            'flow_inconsistent_flows': (flow_metrics['inconsistent_flows'] if flow_metrics is not None else None),
        }
        diagnose_output_path = os.path.join(
            res_path,
            dataset_name + '_' + train_set_name + '_diagnose_eval_results.csv'
        )
        pd.DataFrame([diagnose_summary]).to_csv(diagnose_output_path, index=False)
        print(f"Diagnose eval summary saved to: {diagnose_output_path}")
